name: .NET Build

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: Checkout Meadow.Contracts
      uses: actions/checkout@v4
      with:
        repository: WildernessLabs/Meadow.Contracts
        path: Meadow.Contracts
        ref: develop
        
    - name: Checkout Meadow.Logging
      uses: actions/checkout@v4
      with:
        repository: WildernessLabs/Meadow.Logging
        path: Meadow.Logging
        ref: develop
        
    - name: Checkout Meadow.Units
      uses: actions/checkout@v4
      with:
        repository: WildernessLabs/Meadow.Units
        path: Meadow.Units
        ref: develop
    
    - name: Checkout Meadow.Core
      uses: actions/checkout@v4
      with:
        repository: WildernessLabs/Meadow.Core
        path: Meadow.Core
        ref: develop
        
    - name: Checkout MQTTnet
      uses: actions/checkout@v4
      with:
        repository: WildernessLabs/MQTTnet
        path: MQTTnet
        ref: develop
        
    - name: Checkout Meadow.Modbus
      uses: actions/checkout@v4
      with:
        repository: WildernessLabs/Meadow.Modbus
        path: Meadow.Modbus
        ref: develop
        
    - name: Checkout Meadow.Foundation
      uses: actions/checkout@v4
      with:
        path: Meadow.Foundation
        repository: WildernessLabs/Meadow.Foundation
        ref: develop
        
    - name: Checkout Customer_ThurstonPUD
      uses: actions/checkout@v4
      with:
        path: Customer_ThurstonPUD
        repository: WildernessLabs/Customer_ThurstonPUD

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version:
          9.0.200
    
    - name: Build Meadow Foundation
      run: dotnet build -c Release Customer_ThurstonPUD/Source/Thurston_Monitor.slnx
